services:
    webserver:
        build:
            args:
                MODSECURITY_ENABLED: ${MODSECURITY_ENABLED}
                PROTOCOL: ${WEBSERVER_PROTOCOL}
            context: ./compose-recipes/webserver
        container_name: ${NAMESPACE}-webserver
        depends_on:
            liferay:
                condition: service_healthy
        ports:
            -   "${WEBSERVER_HOST_PORT}:${WEBSERVER_CONTAINER_PORT}" ## Figure out a way to toggle the first part
        volumes:
            -   webserver:/etc/nginx/conf.d
volumes:
    webserver: