services:
    webserver:
        build:
            context: ./compose-recipes/webserver
            args:
                MODSECURITY_ENABLED: ${MODSECURITY_ENABLED:-false}
                PROTOCOL: ${WEBSERVER_PROTOCOL:-http}
                WEBSERVER_HOSTNAMES: ${WEBSERVER_HOSTNAMES:-localhost}
        container_name: ${NAMESPACE}-webserver
        depends_on:
            liferay:
                condition: service_healthy
        environment:
            -   PROTOCOL=${WEBSERVER_PROTOCOL:-http}
            -   WEBSERVER_HOSTNAMES=${WEBSERVER_HOSTNAMES:-localhost}
            -   WEBSERVER_UPSTREAM_FILE=${WEBSERVER_UPSTREAM_FILE:-upstream.conf}
        ports:
            -   "${WEBSERVER_HOST_PORT}:${WEBSERVER_CONTAINER_PORT}"