FROM busybox:latest

ARG DATA_DIRECTORY=data

COPY --chown=1000:1000 ${DATA_DIRECTORY} /container-data

RUN ([ -d /container-data/sqlserver ] && addgroup --gid 10001 mssql && adduser -S -s /usr/sbin/nologin -h /home/mssql --disabled-password -G mssql -u 10001 mssql) || echo

RUN ([ -d /container-data/sqlserver ] && chown -R 10001:10001 /container-data/sqlserver) || echo

USER 1000