##
## Exclusions
##

    #
    # Input a list of comma delimited paths that will be excluded by the source
    # formatter.
    #
    source.formatter.excludes=\
        **/*license*.xml,\
        bundles/**,\
        compose-recipes/**/ldap-init.ldif,\
        exports/**,\
        scripts/vendor/**