services:
    liferay:
        container_name: ${NAMESPACE}-liferay
        env_file:
            -   path: ./liferay-jvm-opts.env
                required: false
        environment:
            -   GLOWROOT_ENABLED=${GLOWROOT_ENABLED}
            -   LIFERAY_JPDA_ENABLED=true
            -   LIFERAY_DISABLE_TRIAL_LICENSE=true
            -   LIFERAY_UPGRADE_PERIOD_DATABASE_PERIOD_AUTO_PERIOD_RUN=true
        healthcheck:
            interval: 5s
            start_period: 5m
            test: /opt/liferay/health-check.sh
            timeout: 5m
        image: ${LIFERAY_IMAGE_NAME}
        ports:
            -   "${LIFERAY_DEBUG_PORT}:8000"
            -   "${LIFERAY_GOGO_SHELL_PORT}:11311"
            -   "${LIFERAY_PORT}:8080"
        volumes:
            -   ./binds/liferay/deploy:/mnt/liferay/deploy
            -   liferay:/opt/liferay/data
volumes:
    liferay: