#!/bin/bash
echo "Starting client extension zip processing service..."

# 2. Run an infinite loop
while true; do
    echo "Running processing cycle..."
    
    /opt/venv/bin/python /src/process-client-extensions.py
    
    # 3. Sleep for 60 seconds before the next run
    sleep 60
done