services:
    webserver:
        build: ./compose-recipes/webserver-http
        container_name: ${NAMESPACE}-webserver-http
        depends_on:
            liferay:
                condition: service_healthy
        ports:
            -   "${WEBSERVER_HTTP_PORT}:80"
        volumes:
            -   webserver-http:/etc/nginx/conf.d
volumes:
    webserver-http: