services:
    data-helper:
        volumes:
            -   mariadb:/container-data/mariadb
    database:
        build: ./compose-recipes/mariadb
        container_name: ${NAMESPACE}-database-mariadb
        environment:
            -   MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
            -   MARIADB_DATABASE=${DATABASE_NAME}
        healthcheck:
            retries: 10
            start_period: 5m
            test: mysqladmin ping -h localhost && grep 'STARTING_UP' /startup_log.txt
            timeout: 20s
        ports:
            -   "${DATABASE_PORT}:3306"
        ulimits:
            nofile:
                hard: 40000
                soft: 20000
            nproc: 65535
        volumes:
            -   dumps:/docker-entrypoint-initdb.d
            -   mariadb:/var/lib/mysql
volumes:
    mariadb: