services:
    data-helper:
        volumes:
            -   db2:/container-data/db2
    database:
        build: ./compose-recipes/db2
        container_name: ${NAMESPACE}-database-db2
        environment:
            -   COMPOSER_DATABASE_NAME=${DATABASE_NAME}
            -   DB2INSTANCE=db2admin
            -   DB2INST1_PASSWORD=lportal
            -   LICENSE=accept
        healthcheck:
            retries: 10
            start_period: 5m
            test: ./opt/ibm/db2/V11.5/bin/db2gcf -s && grep 'STARTING_UP' /startup_log.txt
            timeout: 20s
        platform: linux/x86_64
        ports:
            -   "${DATABASE_PORT}:50000"
        privileged: true
        volumes:
            -   dumps:/database/data/db2admin/backups
            -   db2:/database/data/db2admin/NODE0000
volumes:
    db2: