USE master;
GO

IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'$(DATABASE_USER)')
	CREATE LOGIN [$(DATABASE_USER)] WITH PASSWORD = N'$(DATABASE_USER_PASSWORD)', CHECK_POLICY = OFF;
GO

USE $(DATABASE_NAME);
GO

IF EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'$(DATABASE_USER)')
	ALTER USER [$(DATABASE_USER)] WITH LOGIN = [$(DATABASE_USER)];
ELSE
	CREATE USER [$(DATABASE_USER)] FOR LOGIN [$(DATABASE_USER)];
GO

IF IS_ROLEMEMBER('db_owner', N'$(DATABASE_USER)') = 0
	ALTER ROLE db_owner ADD MEMBER [$(DATABASE_USER)];
GO
