apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: liferayextensions.lxc.liferay.com
spec:
    group: lxc.liferay.com
    names:
        kind: LiferayExtension
        plural: liferayextensions
        shortNames:
            -   cx
        singular: liferayextension
    scope: Namespaced
    versions:
        -   additionalPrinterColumns:
                -   jsonPath: .status.phase
                    name: Phase
                    type: string
                -   jsonPath: .status.lcp.id
                    name: App-ID
                    type: string
                -   jsonPath: .status.url
                    name: URL                       # <--- NEW COLUMN
                    type: string
                -   jsonPath: .status.image
                    name: Image
                    type: string
            name: v1
            schema:
                openAPIV3Schema:
                    properties:
                        spec:
                            properties:
                                sourcePath: {type: string}
                                zipHash: {type: string}
                            type: object
                        status:
                            properties:
                                image: {type: string}
                                lcp:
                                    type: object
                                    x-kubernetes-preserve-unknown-fields: true
                                message: {type: string}
                                phase: {type: string}
                                url:   {type: string}  # <--- NEW FIELD
                            type: object
                    type: object
            served: true
            storage: true
            subresources:
                status: {}