services:
    database:
        build:
            args:
                SQLSERVER_VERSION: ${SQLSERVER_VERSION}
            context: ./compose-recipes/sqlserver
        container_name: ${NAMESPACE}-database-sqlserver
        deploy:
            resources:
                limits:
                    memory: 4G
                reservations:
                    memory: 4G
        environment:
            -   ACCEPT_EULA=Y
            -   COMPOSER_DATABASE_NAME=${DATABASE_NAME}
            -   MSSQL_SA_PASSWORD=Liferay123
        healthcheck:
            interval: 5s
            retries: 50
            start_period: 30s
            test: test -f /tmp/database_exists && /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P Liferay123 -Q  "select name from sys.databases where name = ${DATABASE_NAME}" | grep -q ${DATABASE_NAME}
            timeout: 5s
        ports:
            -   "${DATABASE_PORT}:1433"
        volumes:
            -   dumps:/var/opt/mssql/backups
            -   sqlserver:/var/opt/mssql/data
volumes:
    sqlserver: