jobs:
    validate-database-import:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    submodules: true
            -   uses: actions/setup-java@v4
                with:
                    distribution: zulu
                    java-version: "21"
            -   run: ./scripts/vendor/bats/bin/bats ./scripts/tests/test-database-import.test.sh
name: Validate database import
on: [workflow_dispatch]